### ISSUE TITLE
Provide an easy way to seed data for local development using fixtures (or harvest some content from pod.stanford.edu?)

### ISSUE THREAD

**Issue by cbeer** [ivplus/aggregator#177]
This might have some relation to #172 / #176, if those endpoints are performant enough to get some data (and we had some way to identify records)

(Note: Harvesting content direct from POD may have some additional utility proving that data can be synced from POD for other purposes too, so it should consume our "public" APIs. )

**Comment by jkeck** [comment]
We have a couple possible avenues here, which we might want to explore more based on what our end goal is.

1. If we want to be able to simulate a "Hydrated Data Lake UI" then we might want to extend/enhance our current JSON responses to be able to facilitate access to data that is similar to what institutions are uploading (e.g. multiple files each containing multiple MARC records uploaded to a stream).  This would likely allow us to "sync" this with the latest files in the defaults stream (which means the UI could change, but would be "hydrated" with live data on-demand).

2. Another option would be to use the ResourceSync endpoints to download the full dumps.  Not sure if this is what is meant by "proving that data can by synced from POD", but if we wanted to validate that, I feel like we might not end up getting a good resulting hydrated UI for development (because that's likely not how data will end up being ingested into the system).

3. Another approach worth exploring?
