### ISSUE TITLE
Spike opportunity?: Create a swagger API specification for client upload interactions:

### ISSUE THREAD

**Issue by cbeer** [ivplus/aggregator#5]
Current API actions:
- getting (or using) an organization's JWT token
- uploading a file or multiple files to an organization
- downloading a file or multiple files from an organization

**Comment by birkin** [comment]
@cbeer -- was going to link to this info, but figured I'd embed it here; feel free to close issue unless you think it'd be useful for others to update it.

---

# POD / Swagger-OpenAPI thoughts...

## Summary
- [Swagger](https://en.wikipedia.org/wiki/Swagger_(software))/[OpenAPI](https://en.wikipedia.org/wiki/OpenAPI_Specification) is cool and useful but not necessary for the initial aggregator release. Instead, a simple documentation page could more easily achieve the necessary goals.

## Investigation notes

### Qualifiers
- This was a _very_ time-limited investigation, both in terms of number of days, and total-time spent.
- I and Justin had very little knowledge of Swagger before this spike (more like 'pin') investigation, other than that I'd used the interface (not knowing it was Swagger-generated) when learning about the [Sierra-API](https://catalog.library.brown.edu//iii/sierra-api/swagger/index.html).
- It's definitely possible that someone with a solid knowledge of Rails and Swagger could find a gem that would make implementation reasonably easy for the aggregator's initial release.

### Investigation
- I figured I'd google a bit, then try to find a python-package I could try integrating into an existing lightweight django-api webapp to better grok what creating the interface entailed. (Yes, POD is rails-based, but our knowledge of python is much deeper, so for this learning phase we figured this was a reasonable decision.) Justin also researched a bit, and looked into a [swagger.io](https://swagger.io/) online demo configurator that we briefly explored.

### Notes for future spelunkers
- A few years ago Swagger split into Swagger (for tooling) and OpenAPI (the specification), so sometimes references are intermingled.
- The promise of the tooling -- __as I understand the ecosystem__ -- is that you can use tooling to do two things:
  - create an OpenAPI-compliant configuration json file (which can be rendered via javascript into the beautiful documentation page as shown in the Sierra-API example).
  - given that configuration file, _also_ create libraries in different languages to utilize the api.
- Example: when I was learning about the Sierra-API, I used the web-page to see how to formulate api calls (using proper root-urls and parameters). Then I created a sierra.py python file that I called from my code. It contained functions like get_authentication_token( username, password ), etc. My understanding, now, is that because of the specification, I could have used swagger-tools to use that specification to auto-create that sierra library automatically, with gets/posts/updates to all appropriate endpoints, in a wide variety of languages. Very cool and useful!
- One thing I'm curious about is whether there are django-python-packages/rails-gems that can utilize the existing url-structure of the web-framework to help automate the creation of the configuration json file. That would be nice because it would help minimize the chance that changes to urls could become out-of-sync with the documentation.

---
